# Generated by Django 4.1.3 on 2022-12-10 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_album_alter_profile_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=models.URLField(default=1, verbose_name='Image URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Album Name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
